# Edit the project name, as desired for a new snakemake run:
project: 'skin-microbiome'
# Edit the file address so that bioprojects_list points to the correct list of ENAs Bio-Project IDs:
bioprojects_list: 'data/ncbi_skin-metagenome_sampleIDs.txt'
# Edit the file address so that you can categorize the desired target columns, appropriately.
config_metadata_categories: 'workflow/config/skin-microbiome_config_metadata_categories.tsv'
# Edit the file address so that you download the desired FASTQ files before launching the main app 
# (the functionality is also implemented in the app).
config_fastq_downloads: 'workflow/config/skin-microbiome_config_fastq_downloads.tsv'
# Edit the bowtie2db_version name if pertinent.
bowtie2db_version: 'mpa_vJan21_CHOCOPhlAnSGB_202103' ### vJan25_CHOCOPhlAnSGB_202503
# Path to the YAML describing the conda environment to be used.
# It can be replaced with the path to the created conda environment: .../envs/microbial-distribution-map (see README.md)
conda_env: 'envs/microbial-distribution-map.yaml'